name: Build, test, and deploy to production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  wait-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6

      - name: Wait for 15 seconds
        run: sleep 15
