name: Merge into prod

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      sourceBranch:
        description: "Branch to merge into production"
        required: true
        default: "beta"
      mainBranch:
        description: "Production branch to merge into"
        required: true
        default: "main"
      dryRun:
        description: "Perform a dry run merge (do not push changes)"
        required: false

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs['sourceBranch'] }}
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        # Check if "Read and write permissions" are enabled in Settings -> Actions -> General -> Workflow permissions
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Build status report
        run: |
          echo ${{ github.actor }} is merging ${{ github.event.inputs['sourceBranch'] }} into ${{ github.event.inputs['mainBranch'] }} branch.
          if [ "${{ github.event.inputs['dryRun'] }}" = "true" ]; then
            echo "This is a dry run, changes will not be pushed".
          else
            echo "Pushing changes to ${{ github.event.inputs['mainBranch'] }} branch"
          fi

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge source branch to production
        run: |
          git checkout ${{ github.event.inputs['mainBranch'] }}
          git merge --ff-only ${{ github.event.inputs['sourceBranch'] }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.event.inputs['mainBranch'] }}
          # TODO: FIXME: Using GITHUB_TOKEN does not trigger a push event
          # https://github.com/marketplace/actions/github-push#example-workflow-file
          # github_token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.PAT }}
