name: Merge into prod

on:
  workflow_dispatch:
    # Allows you to run this workflow manually from the Actions tab

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          ref: beta
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        # Check if "Read and write permissions" are enabled in Settings -> Actions -> General -> Workflow permissions
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch all branches
        # Fix for "refusing to merge unrelated histories" error
        # https://github.com/actions/checkout/issues/125
        run: git fetch --all --unshallow

      - name: Merge beta to main
        run: |
          git checkout main
          git merge --ff-only beta
          git push origin main --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
