name: Merge into prod

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      sourceBranch:
        description: "Branch to merge into production"
        required: true
        default: "beta"
      mainBranch:
        description: "Production branch to merge into"
        required: true
        default: "main"
      dryRun:
        description: "Perform a dry run merge (do not push changes)"
        required: false
        default: "false"

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
        with:
          ref: ${{ github.event.inputs['sourceBranch'] }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        # Check if "Read and write permissions" are enabled in Settings -> Actions -> General -> Workflow permissions
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Fetch all branches
        # Fix for "refusing to merge unrelated histories" error
        # https://github.com/actions/checkout/issues/125
        run: git fetch --all --unshallow

      - name: Merge source branch to production
        run: |
          git checkout ${{ github.event.inputs['mainBranch'] }}
          git merge --ff-only ${{ github.event.inputs['sourceBranch'] }}
          if [ "${{ github.event.inputs['dryRun'] }}" = "true" ]; then
            echo "This is a dry run, changes will not be pushed".
            git push origin ${{ github.event.inputs['mainBranch'] }} --dry-run
          else
            echo "Pushing changes to ${{ github.event.inputs['mainBranch'] }} branch"
            git push origin ${{ github.event.inputs['mainBranch'] }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
